### ISSUE TITLE
Stuck after passport upload

### ISSUE THREAD

**Issue by mistersimon** [onfido/onfido-sdk-ui#1165]
### What was the expected behaviour?

After uploading the passport photo, it should proceed to the facial check

### What happened instead?

Users are reporting that they get "stuck" after they start uploading the passport. From the screenshots I've seen its either stuck on the loading animation or shows a blank page with the back button.

![photo_2020-08-22_11-17-42](https://user-images.githubusercontent.com/779959/91923899-07848980-ed04-11ea-8772-754128da0972.jpg)

Unfortunately I couldn't find the offending line of code from the screenshot above, but I can't find any usage of the length property within our code so hopefully it helps a bit.

### Version info:

- Onfido SDK: 5.12.0 / 5.13.0 (Issue still being reported after updating to latest version 
- OS: Windows, Android, IOS
- Browser
- Device
- Node
- Framework or relevant dependencies (if applicable): React

### Integration configuration:

```
onfido = init({
  useModal: true,
  isModalOpen: true,
  onError: () => {
    log.error('Error in onfido modal');
    log.error(err);
  },
  onModalRequestClose: () => {
    // Update options with the state of the modal
    onfido.setOptions({ isModalOpen: false });
    onfido.tearDown();
    onClose();
  },
  // the JWT token that you generated earlier on
  token,
  // id of the element you want to mount the component on
  containerId: 'onfido-mount',
  onComplete: handleComplete,
  userDetails: {
    smsNumber: phoneNumber,
  },
  steps: [
    {
      type: 'document',
      options: {
        documentTypes: {
          passport: true,
        },
      },
    },
    {
      type: 'face',
      options: {
        requestedVariant: 'video',
        // Force them to take photo
        uploadFallback: false,
      },
    },
    'complete',
  ],
});
```

### Steps to reproduce:
Haven't managed to reproduce myself

![photo_2020-09-02_10-00-18](https://user-images.githubusercontent.com/779959/91923564-40702e80-ed03-11ea-8338-05a1dbf4e20c.jpg)
![unnamed](https://user-images.githubusercontent.com/779959/91923566-4108c500-ed03-11ea-89fd-284d19640c7a.jpg)

**Comment by ravinpatel** [comment]
I am also experiencing the same as the author^

**Comment by stefaniacardenas** [comment]
Thanks for raising this issue. I haven't been able to reproduce it but I just raised a PR for what I suspect could be the cause of this issue.

**Comment by stefaniacardenas** [comment]
My fix is unrelated to the `length` error but it would fix the blank screen issue.

**Comment by mistersimon** [comment]
Thanks @stefaniacardenas for looking into this so swiftly :)

Will keep an eye out for a new release!

**Comment by ravinpatel** [comment]
Thanks @stefaniacardenas ! we seem to get the error `Cannot read property 'valid' of undefined`
<img width="1227" alt="Screenshot 2020-09-03 at 09 48 30" src="https://user-images.githubusercontent.com/14273533/92092960-aa9fd680-edca-11ea-8f80-8d91d32a9ce1.png">

**Comment by ravinpatel** [comment]
^ this has been a persistent error since yesterday. 
![Onfido-issue](https://user-images.githubusercontent.com/14273533/92097236-c063ca80-edcf-11ea-8b82-e3bc9382b76e.gif)

**Comment by ravinpatel** [comment]
Response before:
![image (6)](https://user-images.githubusercontent.com/14273533/92103746-4dab1d00-edd8-11ea-9641-afd142fbf07e.png)

Response now:
![image (7)](https://user-images.githubusercontent.com/14273533/92103775-5865b200-edd8-11ea-9ee4-77a730fe5d96.png)

**Comment by tiamen** [comment]
I think the issue is the use of PDF instead of photos

**Comment by kopijunkie** [comment]
Hi @ravinpatel
 
Thank you for the error details and the helpful animation also. 

I believe your issue is different from the one originally reported, but we've identified the issue and have a hotfix for the back end service in the works already. Looking to have this released by tomorrow latest.

**Comment by kopijunkie** [comment]
It is indeed affecting PDF file type document uploads only from what we've found.

**Comment by ravinpatel** [comment]
Hi @kopijunkie thank you for your quick response! Please keep me updated :)

**Comment by kopijunkie** [comment]
@ravinpatel We've just released the hotfix for the issue you reported. So users should no longer be stuck from completing the IDV flow when uploading a PDF file at the document upload screen. Since it is a back end fix you won't need to do anything on your end.

Will keep this issue open as the original issue's fix is still in progress.

**Comment by ravinpatel** [comment]
@kopijunkie Thank you! 👍

**Comment by stefaniacardenas** [comment]
A fix for the blank screen issue has been released in version `6.0.0`.

**Comment by mistersimon** [comment]
Hi, I have upgraded to v6.0.0 - but I still have users experiencing this issue. 


I set up sentry.io after submitting the error to try and help catch/debug the error and still see the `Cannot read property 'length' of undefined`. 
I haven't managed to setup the source maps in sentry, but can share the stack trace on the minified javascript:

https://sentry.io/share/issue/542956502b1a43d28710f1519e19c8e5/

For reference the sequence of events:
![image](https://user-images.githubusercontent.com/779959/94898374-0b065e80-04c4-11eb-8d7f-ce55a4fed9f1.png)
The first two are the user clicking the button to load the modal and fetching the sdk-token to pass to the onfido-sdk

Thanks,
Simon
