### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by nathanredblur** [onfido/onfido-sdk-ui#1659]
### What was the expected behaviour?

Allow me to close onfido without TypeError

### What happened instead?

show this error
```
Uncaught TypeError: Cannot read properties of undefined (reading 'call')
```
that happens in this lines
```
w()(bn()(o), "getNoResultsTextForDropdown", (function() {
                return Object(Pn.n)(o.props.translate("country_select.alert_dropdown.country_not_found"), (function(e) {
                    return e.text
                }
                ))
            }
```
on try to read `translate` in an undefined object.

### Version info:

- Browser onfido_sdk_version 6.15.5

### Integration configuration:

```
getOnfidoSteps = () => {
    const { data } = this.props;
    const steps = [];
      const { documentTypes } = data.onfidoSdk;
      steps.push({
        options: {
          documentTypes: {
            driving_licence: documentTypes.includes('driving_licence'),
            national_identity_card: documentTypes.includes('national_identity_card'),
            passport: documentTypes.includes('passport'),
          },
        },
        type: 'document',
      });
    }

    return steps;
  };

componentDidUpdate(prevProps) {
  this.onfido = init({
            containerId: 'onfido-mount',
            language: user.preferences.profile.language,
            onComplete: this.onComplete,
            steps: this.getOnfidoSteps(),
            token: data.onfidoSdk.token,
            userDetails: {
              smsNumber: `${user.phoneCountryCode}${user.phone}`,
            },
    });
}

componentWillUnmount() {
    if (this.onfido) {
      this.onfido.tearDown();
    }
  }
```

### Steps to reproduce:

Steps to reproduce.
1. Initialize onfido (I do inside a pop-over)
2. click in "Identity Card"
3. click in "search country" dropdown
4. when the list appear, remove onfido (close the pop-over /unload component)

**Comment by onfido-ios-team** [comment]
Hi @nathanredblur 

Sorry for the delay. We are still investigating this case. We will keep you updated with the progress of this ticket accordingly.

Thank you for your patience.

**Comment by it-ony** [comment]
Fixed and released.

**Comment by nathanredblur** [comment]
this issue still happening in version 6.19.0. @it-ony

**Comment by tomdmason** [comment]
@it-ony This error is still happening for us in v8.0.1

**Comment by thexpand** [comment]
This is still happening. Using it in a React application with Next.js 13 app dir. I'm suspecting it has something to do with the SDK not being cleaned up for some reason, but I already have `instance.safeTearDown();` in my clean-up return function of the `useEffect`, so that shouldn't be the issue.
- Next version: `^13.4.19`
- React version: `18.2.0`
- Onfido SDK version: `^13.3.1`
